language: node_js

node_js:
  - 10.12.0

build:
  ci:
    - npm install
    - npm build
    - npm test

  post_ci:
    - cp ./coverage/junit.xml shippable/testresults/
    - cp ./coverage/junit.xml shippable/codecoverage/

  on_failure:
    - cp ./coverage/junit.xml shippable/testresults/
    - cp ./coverage/junit.xml shippable/codecoverage/

integrations:
  notifications:
    - integrationName: webhook
      type: webhook
      on_success: always
      on_failure: never
      on_cancel: never
