language: node_js

node_js:
  - 12.4.0

build:
  ci:
    - npm install
    - npm build
    - npm test

  post_ci:
    - cp ./coverage/junit.xml shippable/testresults/
    - cp ./coverage/junit.xml shippable/codecoverage/

  on_failure:
    - cp ./coverage/junit.xml shippable/testresults/
    - cp ./coverage/junit.xml shippable/codecoverage/

integrations:
  notifications:
    - integrationName: time-tracker-web-dockerhub-build-webhook
      type: webhook
      branches:
        only:
          - master
      on_success: always
      on_failure: never
      on_cancel: never
